/**
 * Writes `design/cupertino-lockup.svg` — the icon and the word on one plate,
 * for the top of the README.
 *
 * It is the last link in the chain `make icon` runs, and it reads the previous
 * link's output rather than the source:
 *
 *   design/cupertino-mark.svg --make icon--> design/cupertino-icon.svg
 *                                              --this--> design/cupertino-lockup.svg
 *
 * Reading the icon rather than the mark is deliberate. The plate gradient, the
 * corner radius and the clip that keeps the hills from squaring off the bottom
 * corners all live in the icon, and re-deriving any of them here would be a
 * second copy of geometry that is supposed to have exactly one.
 *
 * Composition and every assertion live in scripts/lib/lockup.mjs; this file is
 * the IO around them. No dependencies — it only ever writes text.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { composeLockup } from "./lib/lockup.mjs";

const design = join(dirname(fileURLToPath(import.meta.url)), "..", "design");

/** Loud on a missing source: a silent skip here leaves a stale lockup in place. */
const source = async (name) => {
  try {
    return await readFile(join(design, name), "utf8");
  } catch {
    throw new Error(
      `design/${name} is missing. It is generated by \`make icon\` at the repo root — run that first.`,
    );
  }
};

const svg = composeLockup(
  await source("cupertino-icon.svg"),
  JSON.parse(await source("colors.json")),
);

await writeFile(join(design, "cupertino-lockup.svg"), svg);
console.log("  wrote design/cupertino-lockup.svg");
