// Generated by `make revocations`. Do not edit by hand.
//
// Revocation lands at build time rather than run time, which is the price of the
// no-network claim: a refunded key keeps working until the next release, and
// then stops. EULA §4(a) says so to the buyer rather than leaving it to be
// discovered, and docs/licensing.md records why the trade is worth it.
//
// Committed rather than fetched during CI on purpose. Reading D1 from the
// release job would put a network dependency in the path of shipping, where an
// outage at Cloudflare becomes an outage in releases — and buy nothing, since a
// revocation cannot take effect before the next build regardless.

enum Revocations {
  static let ids: Set<String> = [
    "01M0K3QSKCDHPXF14CMNJS0BK2",
    "01M0KWV15Q1H65T87RCW5QZNAA",
  ]
}
