/**
 * Regenerates every mark the site serves, from the repo-root `design/`.
 *
 * `design/cupertino-icon.svg` is itself generated — `make icon` builds it from
 * `design/cupertino-mark.svg`, the same geometry it compiles into the app's
 * Icon Composer bundle. So the chain is one mark end to end:
 *
 *   design/cupertino-mark.svg --make icon--> design/cupertino-icon.svg
 *                                              --pnpm icons--> public/*
 *
 * It used to stop short: these files were hand-copied from a gitignored design
 * directory, and they drifted — the site was serving an earlier direction of the
 * mark than the app shipped. Copying by hand is what this script exists to stop,
 * so run `pnpm icons` after `make icon` rather than moving files yourself.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

const here = dirname(fileURLToPath(import.meta.url));
const pub = join(here, "..", "public");
const design = join(here, "..", "..", "..", "design");

/** Loud on a missing source: a silent skip here ships a stale mark. */
const source = async (name) => {
  try {
    return await readFile(join(design, name), "utf8");
  } catch {
    throw new Error(
      `design/${name} is missing. It is generated by \`make icon\` at the repo root — run that first.`,
    );
  }
};

/**
 * Throws rather than passing the artwork through unchanged, so a change to what
 * `make icon` emits surfaces here instead of silently producing a wrong icon.
 */
const replaceOnce = (text, find, replacement, what) => {
  if (!text.includes(find)) throw new Error(`${what}: expected to find ${find}`);
  return text.replace(find, replacement);
};

const png = async (svg, out, size) => {
  const buf = await sharp(Buffer.from(svg), { density: 400 }).resize(size, size).png().toBuffer();
  await writeFile(join(pub, out), buf);
  console.log(`  ${out}  ${size}×${size}`);
};

console.log("icons →");

const icon = await source("cupertino-icon.svg");
const menubar = await source("cupertino-menubar.svg");

// Served as-is: /favicon.svg is linked by every page and /app-icon.svg is the
// press-kit download, so both have to exist in the built site.
await writeFile(join(pub, "app-icon.svg"), icon);
await writeFile(join(pub, "favicon.svg"), icon);
await writeFile(join(pub, "menubar-glyph.svg"), menubar);
console.log("  app-icon.svg, favicon.svg, menubar-glyph.svg  copied from design/");

await png(icon, "favicon-32.png", 32);

// iOS applies its own mask to the touch icon, so the plate is squared first —
// otherwise the corner radius is applied twice and the artwork reads pinched.
// `make icon` adds this clip-path for the web; here it comes back off.
await png(
  replaceOnce(icon, ' clip-path="url(#c)"', "", "apple-touch-icon"),
  "apple-touch-icon.png",
  180,
);

// The OG card is the mark on the page's own background, so a shared link
// matches the site it opens.
const mark = await sharp(Buffer.from(icon), { density: 400 }).resize(300, 300).png().toBuffer();
const [w, h] = [1200, 630];
await writeFile(
  join(pub, "og-image.png"),
  await sharp({
    create: { width: w, height: h, channels: 4, background: { r: 11, g: 12, b: 15, alpha: 1 } },
  })
    .composite([{ input: mark, top: (h - 300) / 2, left: (w - 300) / 2 }])
    .png()
    .toBuffer(),
);
console.log(`  og-image.png  ${w}×${h}`);
