/**
 * Regenerates every mark the site serves, from the repo-root `design/`.
 *
 * `design/cupertino-icon.svg` is itself generated — `make icon` builds it from
 * `design/cupertino-mark.svg`, the same geometry it compiles into the app's
 * Icon Composer bundle. So the chain is one mark end to end:
 *
 *   design/cupertino-mark.svg --make icon--> design/cupertino-icon.svg
 *                                              --pnpm icons--> public/*
 *
 * It used to stop short: these files were hand-copied from a gitignored design
 * directory, and they drifted — the site was serving an earlier direction of the
 * mark than the app shipped. Copying by hand is what this script exists to stop,
 * so run `pnpm icons` after `make icon` rather than moving files yourself.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

import { composeCard } from "../../../scripts/lib/lockup.mjs";
import { SOCIAL_CARD } from "../src/config.ts";

const here = dirname(fileURLToPath(import.meta.url));
const pub = join(here, "..", "public");
const design = join(here, "..", "..", "..", "design");

/** Loud on a missing source: a silent skip here ships a stale mark. */
const source = async (name) => {
  try {
    return await readFile(join(design, name), "utf8");
  } catch {
    throw new Error(
      `design/${name} is missing. It is generated by \`make icon\` at the repo root — run that first.`,
    );
  }
};

/**
 * Throws rather than passing the artwork through unchanged, so a change to what
 * `make icon` emits surfaces here instead of silently producing a wrong icon.
 */
const replaceOnce = (text, find, replacement, what) => {
  if (!text.includes(find)) throw new Error(`${what}: expected to find ${find}`);
  return text.replace(find, replacement);
};

const png = async (svg, out, size) => {
  const buf = await sharp(Buffer.from(svg), { density: 400 }).resize(size, size).png().toBuffer();
  await writeFile(join(pub, out), buf);
  console.log(`  ${out}  ${size}×${size}`);
};

console.log("icons →");

const icon = await source("cupertino-icon.svg");
const menubar = await source("cupertino-menubar.svg");

// Served as-is: /favicon.svg is linked by every page and /app-icon.svg is the
// press-kit download, so both have to exist in the built site.
await writeFile(join(pub, "app-icon.svg"), icon);
await writeFile(join(pub, "favicon.svg"), icon);
await writeFile(join(pub, "menubar-glyph.svg"), menubar);
console.log("  app-icon.svg, favicon.svg, menubar-glyph.svg  copied from design/");

await png(icon, "favicon-32.png", 32);

// iOS applies its own mask to the touch icon, so the plate is squared first —
// otherwise the corner radius is applied twice and the artwork reads pinched.
// `make icon` adds this clip-path for the web; here it comes back off.
await png(
  replaceOnce(icon, ' clip-path="url(#c)"', "", "apple-touch-icon"),
  "apple-touch-icon.png",
  180,
);

// The Stripe product image, shown beside the line item on the hosted checkout.
// It is a URL on Stripe's side, not an upload — `product.images` on the live
// product points here — so the mark on the checkout page changes when the site
// deploys, and never needs the payment link touched. 512 is generous for a
// thumbnail; the plate keeps its own corner radius, because Stripe rounds the
// container far less than the squircle does and cropping would show.
await png(icon, "product-image.png", 512);

// The OG card is what a link to the site looks like on X, Slack and iMessage.
// It is the lockup reversed out of the page's own background, over two lines the
// site owns — composed by scripts/lib/lockup.mjs, which is also what writes the
// README banner, so the artwork cannot fork between the two.
//
// The words come from src/config.ts rather than from here: they are a claim
// about the product, and this file has no business being the authority on one.
//
// `palette: true` because the card is flat ground, one gradient and text — 54 KB
// against 200 KB truecolour, with no banding visible on the icon's sky at this
// size. It is committed to the repo and fetched by every crawler that sees a
// link, so the four bytes an alpha channel would buy are not worth 150 KB.
const card = composeCard(icon, JSON.parse(await source("colors.json")), SOCIAL_CARD);
await writeFile(
  join(pub, "og-image.png"),
  await sharp(Buffer.from(card), { density: 200 }).png({ palette: true }).toBuffer(),
);
console.log(`  og-image.png  ${SOCIAL_CARD.width}×${SOCIAL_CARD.height}`);
